Added UserEditableUpgrade
2 Error Messages : Assets\Scripts\Super Hero\Game\SuperHeroGame.cs(222,39): error CS0118: 'Animation' is a namespace but is used like a type